# Generated by Django 5.1.2 on 2025-01-11 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "private_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("allowed_ips", models.TextField(blank=True, null=True)),
                ("repo", models.CharField(default="repo", max_length=255)),
                ("branch", models.CharField(default="main", max_length=100)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
