# Generated by Django 5.1.2 on 2025-01-11 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafted", "Drafted"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                        ],
                        default="drafted",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drafted", "Drafted"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                            ("deleted", "Deleted"),
                            ("inactive", "Inactive"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("twitter", "Twitter"), ("linkedin", "LinkedIn")],
                        max_length=50,
                    ),
                ),
                ("is_grouped", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_inactive", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "original_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_posts",
                        to="core.post",
                    ),
                ),
                (
                    "post_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="core.postgroup",
                    ),
                ),
            ],
        ),
    ]
