# Generated by Django 5.1.2 on 2025-01-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_postgroup_post"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postgroup",
            name="organization",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_group_organization",
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
    ]
