# Generated by Django 5.1.4 on 2025-01-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_socialmediaaccount_access_id_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='access_token',
            field=models.CharField(max_length=512),
        ),
    ]
