# Generated by Django 5.1.2 on 2025-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="selected_tone",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("casual", "Casual"),
                    ("humorous", "Humorous"),
                    ("empathetic", "Empathetic"),
                    ("persuasive", "Persuasive"),
                    ("friendly", "Friendly"),
                ],
                default="professional",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="shuffle_tones",
            field=models.BooleanField(default=False),
        ),
    ]
