# Generated by Django 5.1.4 on 2025-01-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_selected_tone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_linkedin',
            field=models.BooleanField(default=False, help_text='Enable LinkedIn integration for this organization.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_twitter',
            field=models.BooleanField(default=False, help_text='Enable Twitter integration for this organization.'),
        ),
    ]
