# Generated by Django 5.1.4 on 2025-01-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_has_linkedin_organization_has_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='has_linkedin',
            field=models.BooleanField(default=False, help_text='Enable LinkedIn integration for the organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_twitter',
            field=models.BooleanField(default=False, help_text='Enable Twitter integration for the organization.'),
        ),
    ]
